spring:
  application:
    name: connect-service
  profiles:
    active: dev

  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true


  datasource:
    url: jdbc:postgresql://localhost:5432/connect-service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 600_000
      #!!!!!修改更高，提高连接池数量
      #((核心数 * 2) + 有效磁盘数)
      maximum-pool-size: 4
      #代表最小空g闲连接数,如果没有就是和maximum-pool-size一致
      # !!!!!!!降低空闲连接数，确保在需要时能够升上去，最后处理完成后能降低下来
      minimum-idle: 2
#      如果某个线程没有释放连接，在获取连接 10000 毫秒后，系统会以WARN级别打印线程堆栈
      leak-detection-threshold: 10_000
      #空闲达到10s时直接关停
      idle-timeout: 30_000


logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.orm.jpa: ERROR
    org.springframework.transaction: ERROR
    com.howtodoinjava: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR
    org.hibernate.type.descriptor.sql: ERROR
    org.springframework.jdbc.core.JdbcTemplate: ERROR
    org.springframework.jdbc.core.StatementCreatorUtils: ERROR
    org.apache.kafka: WARN